[COZY-69] 사용자 상세정보 등록 API
cozy-mate/cozymate-Server pull request #5
Opened 2024-07-23 16:33 UTC by jpark0506

## #️⃣ 요약 설명
사용자의 상세정보를 등록하는 API를 구현했습니다.
## 📝 작업 내용

### 1. MemberStat 도메인 파일 구조 변경

- domain
    - memberstat
        - controller
        - dto
        - entity
        - enums
        - repository
        - service

### 2.Member와 MemberStat의 관계 변경

Member와 MemberStat의 기존 관계는 상속 관계였습니다.
이 관계를 유지하면서 사용하려고 했으나, @Builder를 부모와 자식 모두에 사용하면, 자식 @Builder에서 오류가 발생했습니다.
이것이 발생하는 이유는 @Builder Annotation을 사용한 초기화를 하게 될 때, 자식클래스에서 부모클래스의 멤버 변수를 발견하지 못해 초기화에 실패하기 때문에 발생하는 현상입니다.

이에 대해 @SuperBuilder를 사용할 경우를 생각해보았으나,만약 사용할 경우 부모와 자식 모두 @SuperBuilder를 사용해야합니다.
저희 프로젝트는 모든 Entity가 BaseTimeEntity를 상속하고 있어,
BaseTimeEntity - Member - MemberStat만 있는 것이 아니라,
하위에 여러 Entity가 있기 때문에 모든 Entity에서 @SuperBuilder를 사용해야합니다.
이에 코드 변경 부담이 커, 왜래키를 사용하는 방식으로 관계를 변경했습니다.

**Member - MemberStat의 관계를 OnetoOne으로 바꿨습니다.**
```java
//Member.java
// 기존에 member -> memberstat 상속 관계를
// member <-> memberstat one to one mapping으로 변경하였습니다.
    @OneToOne(mappedBy = "member")
    private MemberStat memberStat;
```

```java
//MemberStat.java
    @OneToOne
    @JoinColumn(name = "member_id", referencedColumnName = "id")
    private Member member;
```

### 3. University 매핑 관계 변경
저번 정기회의 때 언급되었던, University의 연관관계를 Member에서 MemberStat으로 변경하였습니다.
필수로 필요한 정보들은 University에 넣는 것으로 이해했고, 이외 정보들은 MemberStat으로 들어가는 것으로 이해했습니다.
```java
//MemberStat.java
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "university_id")
    private University university;
```

### 4. University Json Data Type 변경
List<Long> → List<String>으로 변경하였습니다.
각 학교의 학과의 Json 형태는 다음과 같이 들어갈 것이라고 생각했습니다.
```json
["컴퓨터공학과","정보통신공학과",...]
```
```java
//University.java
    @Type(JsonType.class)
    @Column(columnDefinition = "json")
    private List<String> departments;
```

### 5. Exception Handler 및 도메인별 예외 코드 추가

예외가 발생하는 경우를 예상해 보았을 때, 3가지 경우가 있어 추가했습니다.
1. 멤버 ID를 찾지 못하는 경우
2. 학교 ID를 찾지 못하는 경우
3. 이미 상세 정보를 입력했음에도 POST 요청을 통해 다시 생성하려고 하는 경우

```java
//ErrorStatus.java
    // Member 관련 에러
    _MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "MEMBER400", "멤버를 찾을 수 없습니다."),

    // University 관련 에러
    _UNIVERSITY_NOT_FOUND(HttpStatus.NOT_FOUND,"UNIVERSITY400","대학을 찾을 수 없습니다."),

    // MemberStat 관련 에러
    _MEMBERSTAT_EXISTS(HttpStatus.BAD_REQUEST,"MEMBERSTAT400","멤버 상세정보가 이미 존재합니다."),
    ;
```
**Handler 파일들**
<img width="420" alt="image" src="https://github.com/user-attachments/assets/0fc84ed2-7459-43dd-ac98-0572de846474">

**Service에서 적용한 예외 처리들**
```java
//MemberStatCommandServiceImpl
@Override
    public Long createMemberStat(Long memberId, MemberStatRequestDTO memberStatRequestDTO) {

        if (memberStatRepository.findByMemberId(memberId).isPresent()) {
            throw new MemberStatHandler(ErrorStatus._MEMBERSTAT_EXISTS);
        }

        Member member = memberRepository.findById(memberId)
            .orElseThrow(()->new MemberHandler(ErrorStatus._MEMBER_NOT_FOUND));
        University university = universityRepository.findById(memberStatRequestDTO.getUniversityId())
            .orElseThrow(()->new UniversityHandler(ErrorStatus._UNIVERSITY_NOT_FOUND));

        Integer admissionYear = Integer.parseInt(memberStatRequestDTO.getAdmissionYear());
```

### 6. @Valid를 사용한 예외 처리

Valid를 사용해 DTO단에서 예외 처리를 했습니다.
사실 Entity에서 Annotation을 활용해 예외 처리를 하려고 했지만, 에러 내용이 표시되지 않고 500에러가 발생해,
예외 처리가 잘 작동하는 현재 잘 작동하는 방식을 선택했습니다.

**DTO**
```java
//MemberStatRequestDTO.java
@Data
@NoArgsConstructor
@AllArgsConstructor
public class MemberStatRequestDTO {

        @NotNull
        private Long universityId;
        //학번의 경우 처리하기 해애한 부분이 있어, String 2자리로 통일함. EX) 09 학번 -> "09"
        @NotNull
        @Size(min=2,max=2)
        private String admissionYear;
        @NotBlank
        private String major;
        @NotNull
        @Min(2)
        @Max(6)
        private Integer numOfRoommate;
        @NotNull
        private Acceptance acceptance;
        @NotNull
        @Min(0)
        @Max(24)
        private Integer wakeUpTime;
        @NotNull
        @Min(0)
        @Max(24)
        private Integer sleepingTime;
        @NotNull
        @Min(0)
        @Max(24)
        private Integer turnOffTime;
        @NotNull
        private SmokingState smokingState;
        @NotBlank
        private String sleepingHabit;
        @NotBlank
        private String constitution;
        @NotBlank
        private String lifePattern;
        @NotBlank
        private String intimacy;
        private Boolean canShare;
        private Boolean isPlayGame;
        private Boolean isPhoneCall;
        @NotBlank
        private String studying;
        @NotNull
        @Min(1)
        @Max(10)
        private Integer cleanSensitivity;
        @NotNull
        @Min(1)
        @Max(10)
        private Integer noiseSensitivity;
        @NotBlank
        private String cleaningFrequency;
        @NotBlank
        private String personality;
        @NotBlank
        @Size(max=4, min=4)
        private String mbti;
        private Map<String, List<String>> options;
}
```
**Controller**
```java
//MemberStatController.java
    /**
     * [POST] 사용자 상세정보 저장
     */
    @PostMapping("/{memberId}")
    public ApiResponse<Long> createMemberStat(
        @PathVariable("memberId") Long memberId,@Valid @RequestBody MemberStatRequestDTO memberStatRequestDTO) {
        return ApiResponse.onSuccess(memberStatCommandService.createMemberStat(memberId,memberStatRequestDTO));
    }
```
### 7. Submodule ddlauto 상태 변경

ddlauto 가 create에서 update로 변경되었습니다.
내일 DB에 JSON 데이터를 추가하겠습니다.

## 동작 확인

아래 데이터로 먼저 DB에 데이터를 추가했습니다.
```sql
INSERT INTO dev.member (birth_day, gender, persona, created_at, id,updated_at, client_id, name, nickname) VALUES ('2000-05-06', 1, 1, '2024-07-23 09:48:26.000000', 1, '2024-07-23 09:50:02.000000', '1', '박준혁', '포비');
INSERT INTO dev.university (created_at, id, updated_at, mail_pattern, name, departments) VALUES ('2024-07-23 09:28:40.000000', 1, '2024-07-23 09:28:42.000000', 'inha.edu', '인하대학교', '["컴퓨터공학과"]');
```
**Request Body**
```
{
  "universityId":1,
  "admissionYear": 23,
  "major": "컴퓨터공학과",
  "numOfRoommate": 2,
  "acceptance": "ACCEPT",
  "wakeUpTime": 7,
  "sleepingTime": 2,
  "turnOffTime": 19,
  "smokingState": "NO",
  "sleepingHabit": "코골이",
  "constitution": "추위를 많이 타요",
  "lifePattern": "새벽형 인간",
  "intimacy": "어느정도 친하게 지내요",
  "canShare": true,
  "isPlayGame": true,
  "isPhoneCall": true,
  "studying": "때마다 다를 거 같아요",
  "cleanSensitivity": 7,
  "noiseSensitivity": 4,
  "cleaningFrequency": "일주일에 3~4번 하는거 같아요",
  "personality": "조용해요",
  "mbti": "INFP",
  "options": {
    "무조건 지켜줘야 해요!": [
      "서로 집중하는 시간은 방해하지 않기로 해요"
    ],
    "이정도는 맞춰줄 수 있어요!": [
      "일주일에 한 번 밥을 같이 먹는건 할 수 있어요"
    ],
    "이건 절대 안 돼요!": [
      "개인 시간을 방해하는 건 절대 안돼요"
    ]
  }
}{
  "universityId":1,
  "admissionYear": 23,
  "major": "컴퓨터공학과",
  "numOfRoommate": 2,
  "acceptance": "ACCEPT",
  "wakeUpTime": 7,
  "sleepingTime": 2,
  "turnOffTime": 19,
  "smokingState": "NO",
  "sleepingHabit": "코골이",
  "constitution": "추위를 많이 타요",
  "lifePattern": "새벽형 인간",
  "intimacy": "어느정도 친하게 지내요",
  "canShare": true,
  "isPlayGame": true,
  "isPhoneCall": true,
  "studying": "때마다 다를 거 같아요",
  "cleanSensitivity": 7,
  "noiseSensitivity": 4,
  "cleaningFrequency": "일주일에 3~4번 하는거 같아요",
  "personality": "조용해요",
  "mbti": "INFP",
  "options": {
    "무조건 지켜줘야 해요!": [
      "서로 집중하는 시간은 방해하지 않기로 해요"
    ],
    "이정도는 맞춰줄 수 있어요!": [
      "일주일에 한 번 밥을 같이 먹는건 할 수 있어요"
    ],
    "이건 절대 안 돼요!": [
      "개인 시간을 방해하는 건 절대 안돼요"
    ]
  }
}
```

**성공한 Swagger**
<img width="1213" alt="asdfsadf" src="https://github.com/user-attachments/assets/584857ac-684c-45a5-8dcd-9986fd86d2a5">

**Row 정상 생성**
<img width="1047" alt="sadfsadf" src="https://github.com/user-attachments/assets/d8e1b582-4758-4d11-89d1-037a4921a0fb">

**없는 멤버의 상세정보 등록을 요청했을 때**
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/cb6cabd7-a81b-4c4d-9456-4a22d02a9516">

**없는 대학을 받았을 때**
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/9fd84379-8710-4928-8056-0d7d128f4431">

**상세정보가 이미 있는 상태에 [...]

2024-07-24 04:36 UTC, eple0329 requested changes
LGTM! 전반적으로 깔끔하네요! 구현하느라 수고 많으셨습니다!
의견이 좀 많습니다! 아무래도 프로젝트 처음 PR인거라, 제가 생각했던것이랑 느낌이 달라서 그런 것 같은데, 이런식으로 컨벤션을 계속 맞춰가면서 하면 좋을 것 같아요!
다른 서버 분들도 의견 남겨주시면 감사합니다!

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/entity/MemberStat.java
> +    @JoinColumn(name = "member_id", referencedColumnName = "id")
해당 방식에서
`@OneToOne(fetch = FetchType.LAZY)`
의 속성을 추가하면 좋을 것 같습니다. 추가하지 않으면 Eager(즉시 로딩) 방식으로 Member와 함께 MemberStat을 가져오게 되는데, 추후에 로그인 기능이 구현된다면 Member는 로그인 과정에서 이미 가져온 상태일 것이기 때문에, LAZY를 통해 지연 로딩을 하면 DB의 I/O 트래픽을 조금이라도 줄일 수 있을 것 같아요!
[여기 링크 참고](https://ict-nroo.tistory.com/132)하면 좋을 것 같아요!

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
저희 Service 단에서 interface 사용하기로 했었나요?? 사용하자고 했던 것 같기도 하고... 도메인별로 다 나뉘어있고, 도메인 하나에 기능이 많지도 않으니 안써도 된다고 했던거같기도 해서 질문합니당

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryServiceImpl.java
> +public class MemberStatQueryServiceImpl implements MemberStatQueryService {
이 클래스는 DB에 접근해서 데이터를 처리할 때 서비스단과 분리하기 위해서 사용하는건가요??
어떤 용도로 만들어둔건지 궁금합니다

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> +    _MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "MEMBER400", "멤버를 찾을 수 없습니다."),
요 부분에 대해서 의견을 또 나누고싶은게 있었는데, HttpStatus.CONFLICT만 사용할지, 아니면 종류별로 구분해서 사용할지 고민이었습니다.
NOT_FOUND나 BAD_REQUEST와 같이 종류별로 나누는것도 좋긴 하지만, 에러 코드로 MEMBER400과 같이 따로 커스텀 에러코드를 주는데 구분을 안해도 될 것 같아서요! 괜히 구분하는데 시간을 쏟는것보다 개발을 더 많이 하는게 나을거같기도 합니다.

저도 어떻게 해야할지 모르겠어서 여러분들의 의견을 듣고싶습니다!!

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/global/response/handler/MemberHandler.java
이런 도메인별 핸들러가 필요한가요?? 프로젝트의 크기가 크지 않아서 공통 핸들러로도 충분할거라고 생각이 들어서요!
다른 역할이 있는지, 도입해야하는 이유가 무엇인지 궁금합니다!

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandServiceImpl.java
> +            MemberStat.builder()
이런 Builder는 Entity 파일 내에 toEntity 함수를 만들어서 만들어주시고, toEntity 함수를 통해 반환받은 객체를 저장하는 방식으로 구현하는게 어떨까요?? builder가 서비스 단에 있게된다면 추후에 기능 개발을 더 했을 때 코드의 길이가 불필요하게 길어질 것 같습니다.

2024-07-24 04:36 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandServiceImpl.java
> +            .orElseThrow(()->new MemberHandler(ErrorStatus._MEMBER_NOT_FOUND));
MemberHandler가 아닌 GeneralException으로만 사용하는건 어떤가요?? 핸들러 파일에도 의견 남겨두었습니다.
MEMBER_NOT_FOUND와 같이 항상 도메인 관련 정보가 예외 Enum에 있으니 없어도 충분히 구분 가능하지 않을까요??

2024-07-24 06:43 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/MemberStatRepository.java
저희가 도메인은 엔티티로 나눠서 발생한 문제같네요.. 
나중에 확장 전에 도메인을 더 큼직하게 나누고 엔티티랑 레포는 패키지파서 관리하고 도메인별 서비스, 컨트롤러로 나눠도 될거 같네요.. 약간 DDD느낌으로 물론 제가 DDD를 해보고 싶어서 그런거긴합니다 :)
지금 상태에서 Entity는 도메인에 둬도 될거같구요, Repository랑 Controller는 적어도 Controller는 패키지가 있었으면 합니다.
일단 로그인 파트에서 Auth라는 패키지를 만들었는데도 Controller가 2개이상 생길 것 같아서요

2024-07-24 06:43 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
> +        private Integer wakeUpTime;
0-23 혹은 1-24가 맞다고 생각됩니다아

2024-07-24 06:43 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryServiceImpl.java
DAO를 사용하는 Service를 따로 나누신건가요?? 비즈니스로직, DAO 사용로직 이렇게 나누신 느낌인가요??

2024-07-24 06:43 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> +    _MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "MEMBER400", "멤버를 찾을 수 없습니다."),
NOT_FOUND나 BAD_REQUEST일단 놔두고 각자 도메인에서 커스텀에러를 만드는게 좀더 좋아보입니다!!

2024-07-24 06:43 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/global/response/handler/MemberHandler.java
이건 Handler보다는 Exception 아닌가요?? 제가 잘못 이해하고 있는걸까요?

2024-07-24 07:16 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/MemberStatRepository.java
> 저희가 도메인은 엔티티로 나눠서 발생한 문제같네요.. 나중에 확장 전에 도메인을 더 큼직하게 나누고 엔티티랑 레포는 패키지파서 관리하고 도메인별 서비스, 컨트롤러로 나눠도 될거 같네요.. 약간 DDD느낌으로 물론 제가 DDD를 해보고 싶어서 그런거긴합니다 :) 지금 상태에서 Entity는 도메인에 둬도 될거같구요, Repository랑 Controller는 적어도 Controller는 패키지가 있었으면 합니다. 일단 로그인 파트에서 Auth라는 패키지를 만들었는데도 Controller가 2개이상 생길 것 같아서요

도메인을 큼직하게 나누고, 엔티티와 레포를 패키지파서 관리한다는게 도메인 외부에 엔티티, 레포 패키지를 따로 두고 모아둔다는 의미일까요?? (물론 나중에 확장할 때의 일이긴 하지만, 순수하게 궁금해서요!)

--- 
작성하면서 좀 찾아봤는데
[이 사이트](https://www.inflearn.com/questions/16046)와 [이 사이트](https://cheese10yun.github.io/spring-guide-directory)를 참고하면 좋을 것 같아요! 
패키지 구조에 왕도는 없는 것 같고... 저희 서비스의 구성에 따라서 어떻게 구조를 짤지 한번 같이 의견을 나누고 고민해봤으면 좋겠습니다. 물론 지금은 기능 구성에 초점을 맞춰야하겠지만요!
---
그리고 다시 계속 이야기를 해보자면, 처음 개발에서 저는 엔티티 기준으로 나누는게 각자 코드에서의 간섭을 최소화할 수 있을거라 생각해서 이렇게 구성한 것이고... 어느정도 개발이 된 이후에 패키지 구성을 변경해보는게 좋을 것 같다고 생각합니다!
1. 빠른 개발이 필요할 때 패키지 구성을 변경하게 되면, 그로인한 시간 소요가 문제가 될 것이며, 개발중인 모든 작업을 멈추고 처리해야한다.
2. 엔티티를 기준으로 나누는 것이 각자 코드 간섭을 최소화할 수 있다.
라도 제 의견을 정리할 수 있겠네요.

그리고 DDD 느낌이라면 어떤 느낌일까요?? Domain Driven Development인 것 같은데, 말즈가 생각하는 구조를 나중에 같이 생각해보고 배워나갈 수 잇으면 좋을 것 같습니다. DDD 관련해서 참고자료가 있다면 공유해주세요.

그러면 Entity와 Repository만 도메인에 두고, 나머지는 패키지로 감싸서 두는걸로 통일하자는 의견일까요?? Auth에서 Controller가 2개 생긴다는 것은 이해했습니다! 그럴 수 있겠네요

2024-07-24 09:22 UTC, veronees commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
회의에서 제가 질문했던 부분인데 interface 사용하지 않기로 했었습니다..! 그 때 포비가 없을 때 나눈 얘기 같아요

2024-07-24 09:22 UTC, veronees commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandServiceImpl.java
> +            .orElseThrow(()->new MemberHandler(ErrorStatus._MEMBER_NOT_FOUND));
저는 GeneralException으로만 예외처리를 해두긴 했는데.. 도메인용 핸들러를 만들어서 예외처리하는 건 가독성 면에서 더 좋은 것 같고, GeneralException만 사용하는 건 enum 값으로 이미 도메인 정보를 갖고 있어서 간단하고 좋은 것 같다고 생각합니다

2024-07-24 17:30 UTC, suuu0719 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandServiceImpl.java
> +            .orElseThrow(()->new MemberHandler(ErrorStatus._MEMBER_NOT_FOUND));
GeneralException만으로도 예외처리가 가능할 것 같습니다

2024-07-24 18:18 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/MemberStatRepository.java
우선 제가 만든 파일에 대한 구조에 대한 제 의견을 말씀드리겠습니다.

 제가 도메인 안에 파일을 폴더 안에 넣어놓은 이유는, 제가 개발할 때 폴더 안의 파일로 접근하는게 편했기 때문입니다. 

 1개의 파일이기 때문에 폴더에 구분하지 않는 점, 불필요한 이동, 확장성을 생각해보면 장점이 있는 것도 충분히 이해했습니다.

 제가 FE 작업을 주로 하다보니 이런 사고 방식이 고정되어 폴더를 만드는 것이 편할 수도 있는데, 특정 도메인 안의 파일, 폴더가 계층적인 의미를 나타내고 있는 경우가 있습니다. 
같은 경로 내 파일과 폴더가 있으면, 주로 파일 안에 import 하는 구성 요소로, 폴더를 두어 그 안에 구성요소들을 넣는 경우가 많습니다.

 도메인 안의 폴더나 파일들을 보면, 모두 도메인을 구성하는 부품들이고, 서로가 서로 의존하고는 있지만, 도메인이 정상 작동하기 위한 부품들이지, 그렇다고 상속하거나 상위 구성요소라고 보기 어렵다고 생각했습니다. 그래서 모두 동일한 위치인 폴더 내 파일로 통일하고자 했던 것이고, 사실 이런 방식이 형식상 맞다고 생각했고 제 마음이 편했습니다. 

 하지만 이런 방식이 효율성이 낮은 측면이 있는 것도 알고 있기 때문에, 생산성에 영향이 간다면 1개의 파일은 폴더에 넣지 않는 방식으로 전환할 의향도 있습니다.

두번째로, 엔티티로 도메인 구성이 된 부분이 된 것에 대한 제 의견은, 개발자 간의 간섭을 최소화하는 장점이 있다고 그 방식이 서로에게 편하다고 생각합니다. 특히 저희가 엔티티가 있기 때문에, 도메인을 나누는 것이 오히려 기능 개발에 초점을 맞춘다면 장점이 될 것 같네요.

제가 경험한 것을 의견에 보태자면, Context - 기능, 기능 - Context 이 두 가지 방식 중에 저희처럼 많은 Context가 있다면, 전자의 방식이 서로 개발하는데 편했던 것 같습니다.

그래서 제 의견을 정리하자면, 

- 1개의 파일에 유지될 수 있더라도, (폴더 - 파일) 형식을 통일하는 것이 좋을 것 같지만, 생산성 측면에서 효율적이라면, 1개의 파일로 유지될 수 있는 것들을 파일로 둬도 괜찮다.
- 현재 방식대로, 도메인안에 각 기능을 넣는 것이 좋아보입니다.

그리고 저도 말즈가 이야기하는 DDD를 반영하는 구조, 저도 궁금합니다!! 소스 공유해주시면 같이 배워보고 싶네요!

2024-07-24 18:19 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
> +    @PostMapping("/{memberId}")
좋은 생각입니다.
따로 TODO를 만들어 적어놓긴 할 건데, 혹시 추천하시는 방식이 있나요?

2024-07-24 18:35 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
> +        private String sleepingHabit;
좋은 의견 감사합니다.

제가 개발하기 전 도메인을 살펴볼 때, String, ENUM을 엔티티에서 구분하셨길래 무빗의 의도를 파악해 보려고 했습니다. 

그래서 확실하게 변하지 않는 흡연 여부, 합격 여부를 ENUM으로 둔 점, 그리고 나머지 Column들은 확실하게 변한 여지가 있는 부분들은 String으로 두신 것 같았습니다. (지금 생각해보니 합격 여부도 변할 수 있겠네요..)

이러한 생각과 함께 남겨주신 의견과 자료를 읽어보니, ENUM은 사용하지 않겠습니다. 

그 이유는 프로젝트 초기 단계이기 때문에, 기획의 변동 가능성이 높아 값을 자주 수정해줘야 할 수도 있는데, 이럴 경우 해당 도메인 개발자의 개발 자원 소모량이 더 크기 때문입니다. 또한 빠른 개발을 하기 위해서는 제약은 후순위로 미뤄둬도 괜찮다고 생각했습니다!

2024-07-24 18:38 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/entity/MemberStat.java
> +    @JoinColumn(name = "member_id", referencedColumnName = "id")
아하 넵 알겠습니다 감사합니다~!

2024-07-24 18:41 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
감사합니다 확인했습니다!!

2024-07-24 19:07 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandServiceImpl.java
> +            .orElseThrow(()->new MemberHandler(ErrorStatus._MEMBER_NOT_FOUND));
저도 별도의 도메인별 Handler 파일을 만들어서 매번 관리하는 것이 불편하고, GeneralException으로도 도메인 정보를 표현할 수 있으니, GeneralException만 사용하겠습니다!

2024-07-24 19:09 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
> +        private Integer wakeUpTime;
좋은 지적 감사합니다~ 0-23으로 하겠습니다

2024-07-24 19:29 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryServiceImpl.java
> +public class MemberStatQueryServiceImpl implements MemberStatQueryService {
서비스단과 분리하려고 한 것은 아니고, 서비스 안에서 역할을 분리했습니다.

제가 나눈 코드를 살펴보시면, QueryService와 CommandService로 나눠진 것을 보실 수 있습니다.

QueryService는 조회 작업, CommandService는 명령(쓰기, 삭제, 수정) 작업에 사용하려고 했었습니다.

이런 구조는 UMC 워크북에서 처음 봤지만, 관련 구조가 CQRS인 것은 [이 링크](https://docs.aws.amazon.com/ko_kr/prescriptive-guidance/latest/modernization-data-persistence/cqrs-pattern.html), [이 링크] (https://techblog.woowahan.com/7835/) 를 통해 알게 되었습니다.

저는 이런 구조로 만드는 게, 코드의 가독성을 향상 시키고, 한 클래스에서 사용하는 코드량이 줄어 장점이 있다고 생각했습니다. 또한 하나의 파일에서 만드는 것도 좋지만, 역할의 명확한 차이점, DB 변경(ex)create, update, delete)과 DB 조회(ex) findbyId, findAll, search), 가 있기 때문에 이런 방식으로 구조를 만드는 것도 좋다고 생각했습니다.

하지만 이게 개발하는 데는 조금 더 시간이 걸릴 수도 있다고 생각하기도, 일관성 있게 코드를 구성하려면 모두가 잘 이해하고 있는 부분이어야 하기 때문에, 어떻게 하면 좋을 지 모르겠습니다. 다른 분들 의견 부탁드릴게요!!

2024-07-24 19:38 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/global/response/code/status/ErrorStatus.java
> +    _MEMBER_NOT_FOUND(HttpStatus.NOT_FOUND, "MEMBER400", "멤버를 찾을 수 없습니다."),
CONFLICT로 통일하고 커스텀 에러로 정보를 준다면, 개발 생산성에 도움이 될 것 같습니다.

2024-07-24 19:46 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/global/response/handler/MemberHandler.java
프로젝트 크기를 고려하면 따로 Handler가 필요 없을 것 같습니다. 저도 GeneralException을 사용하도록 하겠습니다.

말즈가 지적한대로 도메인 별로 커스텀 예외를 처리하기 위한 파일인데, 클래스 명이 잘못된 것 같아요! MemberException이나 MemberExceptionHandler가 더 적절한 이름이 될 것 같네요~ 좋은 지적 감사합니다!

2024-07-24 19:48 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandServiceImpl.java
> +            MemberStat.builder()
특히 칼럼이 많은 도메인이라 힘들었는데, 이런 방식이 좋을 것 같습니다. 좋은 의견 감사힙니다 반영해보겠습니다!

2024-07-24 19:58 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryServiceImpl.java
저는 DAO를 DB를 사용해 데이터를 조회하거나 조작하는 기능을 담당하는 것, 즉 Repository로 이해하고 있습니다~!

그래서 제가 나눈 구조를 설명하자면, 
DAO 중 Read 기능 이용하는 Service - QueryService
DAO 중 Read를 제외한 나머지 기능을 이용하는 Service - CommandService
로 나누었습니다. 

이런 구조를 CQRS라고 부르고, [이 링크](https://docs.aws.amazon.com/ko_kr/prescriptive-guidance/latest/modernization-data-persistence/cqrs-pattern.html), [이 링크](https://techblog.woowahan.com/7835/)를 참고해주시면 좋을 것 같습니다!!

저는 이런 구조로 만드는 게, 앞서 무빗에게도 동일한 답변을 했지만, 코드의 가독성을 향상 시키고, 한 클래스에서 사용하는 코드량이 줄어 장점이 있다고 생각했습니다. 또한 하나의 파일에서 만드는 것도 좋지만, 역할의 명확한 차이점, DB 변경(ex)create, update, delete)과 DB 조회(ex) findbyId, findAll, search), 가 있기 때문에 이런 방식으로 구조를 만드는 것도 좋다고 생각했습니다.

하지만 이게 개발하는 데는 조금 더 시간이 걸릴 수도 있다고 생각하기도, 일관성 있게 코드를 구성하려면 모두가 잘 이해하고 있는 부분이어야 하기 때문에, 어떻게 하면 좋을지 모르겠습니다. 의견 부탁드릴게요!!

2024-07-24 20:10 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
> +        return ApiResponse.onSuccess(memberStatCommandService.createMemberStat(memberId,memberStatRequestDTO));
저는 직관적인 코드를 선호하기도 하고, 빠른 개발을 위해서 API Response가 좀 더 적절한 방법 같습니다.

2024-07-25 00:46 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
> +    @PostMapping("/{memberId}")
TODO 규칙까지 정하는건 아니지만 저는
// TODO: 07.25. 무슨무슨기능 어떻게 변경 예정
처럼 대충 씁니다~

2024-07-25 00:51 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryServiceImpl.java
> +public class MemberStatQueryServiceImpl implements MemberStatQueryService {
CQRS와 관련된 방식이군요?! 혹시 오늘 회의때 한번 설명해줄 수 있을까요?? 
조회 / 명령을 구분하는 방식으로 개발하는것도 좋아보이네요! 매우 흥미롭습니다...
저는 항상 Service에 모든 코드를 몰아넣어서 코드의 가독성이 좀 떨어진다고 느낀적도 많았기 때문에 이런 식으로 분리하는것도 좋다고 봅니다!

2024-07-25 00:59 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
> +        return ApiResponse.onSuccess(memberStatCommandService.createMemberStat(memberId,memberStatRequestDTO));
[여기 링크를 참고했고](https://velog.io/@kseysh/ResponseEntity-vs-ApiResponse)

```
ApiResponse와 ResponseEntity는 Spring Framework에서 HTTP 응답을 처리하는 데 사용되는 두 가지 다른 접근 방식입니다. 각각의 차이점과 장단점을 설명해 드리겠습니다.

1. ApiResponse

ApiResponse는 사용자 정의 클래스로, 일반적으로 응답 데이터를 캡슐화하는 데 사용됩니다.

장점:
- 응답 구조를 일관되게 유지할 수 있습니다.
- 비즈니스 로직에 특화된 응답을 만들 수 있습니다.
- 직렬화/역직렬화가 쉽습니다.

단점:
- HTTP 상태 코드, 헤더 등을 직접 제어하기 어렵습니다.
- Spring의 기본 기능을 활용하지 않아 추가 작업이 필요할 수 있습니다.

2. ResponseEntity

ResponseEntity는 Spring Framework에서 제공하는 클래스로, HTTP 응답을 나타냅니다.

장점:
- HTTP 상태 코드, 헤더, 본문을 쉽게 제어할 수 있습니다.
- Spring의 기본 기능을 활용하여 더 유연한 응답 처리가 가능합니다.
- RESTful API 설계에 적합합니다.

단점:
- 응답 구조를 일관되게 유지하기 위해서는 추가적인 래퍼 클래스가 필요할 수 있습니다.
- ApiResponse에 비해 사용법이 조금 더 복잡할 수 있습니다.

선택 기준:
- 단순한 데이터 반환이 목적이라면 ApiResponse가 적합할 수 있습니다.
- HTTP 응답을 세밀하게 제어해야 한다면 ResponseEntity가 더 적합합니다.
- RESTful API를 설계한다면 ResponseEntity를 사용하는 것이 좋습니다.

실제 프로젝트에서는 두 접근 방식을 혼합하여 사용하는 경우도 많습니다. 예를 들어, ApiResponse를 ResponseEntity의 본문으로 사용하여 두 방식의 장점을 모두 활용할 수 있습니다.

더 자세한 설명이나 예제 코드가 필요하시다면 말씀해 주세요.
```
요렇게 GPT에게도 물어봤습니다! 

포비의 말에 동의하지 않는것은 아니고, 해당 내용에 도움이 될만한 자료일 것 같아 가져와봤어요!
한번 회의때 이야기해봅시다! 사실 전 이 두 차이를 아직 잘 모르거든요...^^

2024-07-25 01:51 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/controller/MemberStatController.java
> +        return ApiResponse.onSuccess(memberStatCommandService.createMemberStat(memberId,memberStatRequestDTO));
오 저랑 보신 자료가 같아요! 좋습니다 저도 이런 응답 방식이 있다는 걸 무빗 통해서 처음 알게 되어, 조금 더 공부가 필요할 것 같아요..ㅎㅎ

2024-07-25 01:55 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatQueryServiceImpl.java
> +public class MemberStatQueryServiceImpl implements MemberStatQueryService {
넵 맞습니다!!
Service 단에 모든 코드를 넣는 것이, 코드의 가독성에 영향을 준다는 부분에 대해서도 공감하고 있습니다.
회의 때 한번 설명해보도록 하겠습니다!

2024-07-25 02:41 UTC, eple0329 approved these changes
LGTM~ 좋아요좋아요 수고 많았습니다!

2024-07-25 02:41 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/entity/MemberStat.java
> +    public static MemberStat toMemberStat(
작은 의견이긴 하지만 toMemberStat을 사용하는 방식이
`MemberStat.toMemberStat(abcd)`
형식이라서 toMemberStat으로 안해도 되고, toEntity로 구성해도 좋습니다.
toEntity로 구성했을 때의 장점은
- 다른 도메인에서도 엔티티.toEntity라는 공통된 함수를 사용할 수 있기 때문에 통일성 측면에서도 좋다고 생각합니다.

* 이건 의견일 뿐이라서 수정해달라는 것은 아닙니다! 현재 방식이 편하다면 그대로 사용해주세요.

2024-07-25 02:50 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/entity/MemberStat.java
> +    public static MemberStat toMemberStat(
다른 도메인에서의 사용성을 고려하지 않았었는데, toEntity로 구성하는게 통일성 측면에서 장점이 있겠네요! 좋은 의견 감사합니다~반영해보겠습니다!

2024-07-26 10:25 UTC, veronees approved these changes

2024-07-27 13:11 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/member/Member.java
> -    private University university;
대학 가져가신거 확인이염

2024-07-27 13:11 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
> +    public static MemberStat toEntity(
파라미터로 DTO를 받는게 어떨까요? DTO를 파라미터로 넣기가 좀 그러려나 얘기해보면 좋을거 같아요

2024-07-27 13:11 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
> +public class MemberStatRequestDTO {
Nested 클래스로 DTO를 static으로 선언하고 이거를 converter에서 파라미터로 사용하는게 어떨까요

2024-07-27 13:11 UTC, genius00hwan commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/service/MemberStatCommandService.java
> +public class MemberStatCommandService {
저도 최대한 DB접근 Service 나눠보도록 하겠습니다..

2024-07-27 14:45 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
> +    public static MemberStat toEntity(
사실 이 부분에서도 컨벤션을 맞출까 고민했는데, 이거까지 맞추기에는 지금도 충분히 컨벤션이 많아서 이야기는 안했습니당...
toEntity를 위해 파라미터를 넣는게 DTO 자체가 들어갈 때도 있지만, 다른 상황에서 쓰일수도 있고, DB에서 가져와서 사용할 수도 있는것이고... 변수가 많을 것 같다고 생각했기 때문이죠
무엇보다 각자의 취향이 있을거고, 가독성에서도 큰 차이가 있지는 않을 것 같다는 개인적인 느낌적인 느낌이었슴다.

2024-07-27 14:47 UTC, eple0329 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
> +public class MemberStatRequestDTO {
파일별로 DTO를 만들게 아니라면 말즈 의견에 동의합니다~

2024-07-27 14:57 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/dto/MemberStatRequestDTO.java
> +public class MemberStatRequestDTO {
여러 경우가 있을 거 같아서 그럴 것 같네요~ 반영해보겠습니다!

2024-07-27 15:04 UTC, jpark0506 commented on src/main/java/com/cozymate/cozymate_server/domain/memberstat/converter/MemberStatConverter.java
> +    public static MemberStat toEntity(
DTO를 넣고 깔끔하게 코드를 짜고 싶긴 한데, 다른 엔티티에서 정보를 가져오면(memberstat의 경우, member, university) 인자가 더 필요한 경우도 있는 것 같더라고요~ 도메인 안의 Converter의 역할은 DTO <-> Entity라고 이해하고 있는데, 변환하는 역할이라는 큰 틀 안에서 DTO와 필요한 경우 다른 인자가 있어도 괜찮을 것 같습니다!

2024-07-27 19:20 UTC, suuu0719 approved these changes

2024-07-28 05:38 UTC, merged